-- AlterTable
ALTER TABLE "InvoiceItem" ALTER COLUMN "firstWeight" SET DATA TYPE DECIMAL(14,3),
ALTER COLUMN "secondWeight" SET DATA TYPE DECIMAL(14,3),
ALTER COLUMN "netWeight" SET DATA TYPE DECIMAL(14,3);
